name: CI

env:
  CI: true

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*', '**/*']

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORGE_SNAPSHOT_CHECK: true
      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: artifacts/
      - uses: actions/upload-artifact@v4
        with:
          name: built-lib
          path: lib/balancer-v3-monorepo/pkg/
      - uses: actions/upload-artifact@v4
        with:
          name: built-lib-pvt
          path: lib/balancer-v3-monorepo/pvt/

  test-forge:
    runs-on: ubuntu-latest
    needs: lint-and-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-artifacts
          path: artifacts/
      - uses: actions/download-artifact@v4
        with:
          name: built-lib
          path: lib/balancer-v3-monorepo/pkg/
      - uses: actions/download-artifact@v4
        with:
          name: built-lib-pvt
          path: lib/balancer-v3-monorepo/pvt/
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Test
        run: yarn test:forge

  test-hardhat:
    runs-on: ubuntu-latest
    needs: lint-and-build
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - uses: actions/download-artifact@v4
        with:
          name: built-artifacts
          path: artifacts/
      - uses: actions/download-artifact@v4
        with:
          name: built-lib
          path: lib/balancer-v3-monorepo/pkg/
      - uses: actions/download-artifact@v4
        with:
          name: built-lib-pvt
          path: lib/balancer-v3-monorepo/pvt/
      - name: Test
        run: yarn test:hardhat
